### ISSUE TITLE
debug error

### ISSUE THREAD

**Issue by guyulmaz** [jucaesmanhoto/cctdd#1]
when I try to debug the app it is giving error below.

Launching lib\main.dart on Android SDK built for x86 in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\ortam\kod\flutter\works\cctdd-master\build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
Error launching application on Android SDK built for x86.
Exited (sigterm)

I don't get this problem with other applications

**Comment by jucaesmanhoto** [comment]
Are you trying to run it in a real device? It looks like you're out of memory space on it. Try uninstalling some unused apps before run it again.

**Comment by guyulmaz** [comment]
no at android emulator I try to debug. I don't get this problem with other applications

**Comment by guyulmaz** [comment]
I created new emulator with higher harddisk, it solved problem

**Comment by jucaesmanhoto** [comment]
> I created new emulator with higher harddisk, it solved problem

Glad to hear it!
